//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionMonitoring.Models
{
    using System;
    
    public partial class AggregatedRaceResult
    {
        public Nullable<int> RaceID { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PartyName { get; set; }
        public string PartyAcronym { get; set; }
        public string PartyColor { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string RegionName { get; set; }
        public string RegionCode { get; set; }
        public Nullable<int> TotalVotes { get; set; }
    }
}
