//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace ElectionMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public Candidate()
        {
            this.RaceResults = new HashSet<RaceResult>();
        }
    
        public int CandidateID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int PartyID { get; set; }
        public Nullable<int> RaceID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Gender { get; set; }
    
        public virtual Party Party { get; set; }

        public virtual ICollection<RaceResult> RaceResults { get; set; }
    }
}
