//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CategoryID { get; set; }
        public Nullable<bool> TopLevel { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CategoryTypeID { get; set; }
    
        public virtual CategoryType CategoryType { get; set; }
    }
}
