//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public Party()
        {
            this.Candidates = new HashSet<Candidate>();
        }
    
        public int PartyID { get; set; }
        public string Name { get; set; }
        public string Acronym { get; set; }
        public string LogoFile { get; set; }
        public string Color { get; set; }
    
        public virtual ICollection<Candidate> Candidates { get; set; }
    }
}
