//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace ElectionMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceResult
    {
        public int RaceResultID { get; set; }
        public Nullable<int> RaceID { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> NoOfVotes { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    
        [JsonIgnore]
        public virtual Candidate Candidate { get; set; }
        public virtual Race Race { get; set; }
        public virtual Region Region { get; set; }
    }
}
