//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.RaceResults = new HashSet<RaceResult>();
        }
    
        public int RegionID { get; set; }
        public Nullable<bool> TopLevel { get; set; }
        public Nullable<int> ParentRegionID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Name { get; set; }
        public Nullable<int> RegionTypeID { get; set; }
        public string RegionCode { get; set; }
        public string Coordinates { get; set; }
    
        public virtual ICollection<RaceResult> RaceResults { get; set; }
        public virtual RegionType RegionType { get; set; }
    }
}
