//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionType
    {
        public RegionType()
        {
            this.Regions = new HashSet<Region>();
        }
    
        public int RegionTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Region> Regions { get; set; }
    }
}
